---
title: "My paper"
author: "Joe Brew"
date: "`r format(Sys.time(), '%B %d, %Y')`"
fig_height: 2.6
fig_width: 4
output:
  html_document:
    pandoc_args: [
      "+RTS", "-K16000m",
      "-RTS"
    ]
    toc: true
    toc_float: true
    theme: united
---


```{r, echo = FALSE, warning = FALSE, message = FALSE, comment = NA, error= FALSE, cache = F}
# No scientific notation
options(scipen=999)

# Packages 
library(databrew)
library(cism)
library(dplyr)
library(ggplot2)
library(ggmap)
library(gsheet)
library(readr)

# Options for this document (ie, whether to show code, errors, etc.)
knitr::opts_chunk$set(comment = NA, 
               echo = FALSE,
               eval = TRUE,
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = FALSE)

# Read in the data for the survey we took in class the other data
if(!'survey.csv' %in% dir()){
  survey <- gsheet2tbl('https://docs.google.com/spreadsheets/d/1kCpmpVqD4tzkdGgyLQGVqeZG1sJoe2FwFJIxtDRsrb0/edit?usp=sharing')
  write_csv(survey, 'survey.csv')
} else {
  survey <- read_csv('survey.csv')
}
```

# Introduction

This is a research paper about a survey we took in class. It is written in Rmarkdown.

# Methods

There were `r nrow(survey)` participants in the survey.


# Results

## Sub-section 1

Here is some more text.

```{r}
# This is an R comment

# This is some code to produce a barplot of sex 
ggplot(data = survey,
       aes(x = sex)) +
  geom_bar() 
```

## Sub-section 2

# Discussion

Great, even more text.

# Conclusion