---
title: "This is the title of my post"
author: "Xing Brew"
date: "December 4, 2017"
output:
  html_document:
    template: post_template.html
---

```{r setup, include=FALSE}
# Basic knitr options
knitr::opts_chunk$set(comment = NA, 
                      echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE, 
                      error = FALSE, 
                      cache = FALSE)

# Turn off scientific notation
options(scipen = '999')

# Libraries
library(dygraphs)
library(tidyverse)
```

## Introduction  

Here is some text.

Here is a plot

<div class="row">
<div class="3u 12u(narrower)">
</div>

<div class="6u 12u(narrower)">

<div class="image featured">

```{r, echo = FALSE}
barplot(1:10, col = rainbow(10))
```

</div>  
</div>
<div class="3u 12u(narrower)">
</div>
</div>


Here is another.

```{r, fig.width=6, fig.height=2.5}
hw <- HoltWinters(ldeaths)
predicted <- predict(hw, n.ahead = 72, prediction.interval = TRUE)

dygraph(predicted, main = "Predicted Lung Deaths (UK)") %>%
  dyAxis("x", drawGrid = FALSE) %>%
  dySeries(c("lwr", "fit", "upr"), label = "Deaths") %>%
  dyOptions(colors = RColorBrewer::brewer.pal(3, "Set1"))
```

## Conclusion

Here is some text. Here is a [link](http://databrew.cc).